name: CI/CD

on:
  push:
    branches: [ "machine-learning" ]
  pull_request:
    branches: [ "machine-learning" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "npm"

      - name: Angular installation
        run: npm install --global @angular/cli@21.2.13

      - name: Dependencies installation
        run: npm install

      - name: Build
        run: ng build

      - name: Web Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/machine-learning'
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{secrets.FTP_DHL_ORG_MX_SERVER}}
          username: ${{secrets.FTP_DHL_ORG_MX_USER}}
          password: ${{secrets.FTP_DHL_ORG_MX_PASSWORD}}
          local-dir: ./dist/hipotesis-v2/browser/
          server-dir: ${{secrets.FTP_DHL_ORG_MX_DIRECTORY}}
          dangerous-clean-slate: false
